//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_PTUDHTTTHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public DocGia()
        {
            this.Hinhs = new HashSet<Hinh>();
        }
    
        public int id_doc_gia { get; set; }
        public string ma_doc_gia { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string dien_thoai { get; set; }
        public string email { get; set; }
        public string gioi_tinh { get; set; }
        public string bar_code { get; set; }
        public byte[] bar_code_image { get; set; }
        public Nullable<int> id_loai_doc_gia { get; set; }
    
        public virtual LoaiDocGia LoaiDocGia { get; set; }
        public virtual ICollection<Hinh> Hinhs { get; set; }
    }
}
