//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_PTUDHTTTHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hinh
    {
        public int id_hinh { get; set; }
        public string ten_hinh { get; set; }
        public string url_hinh { get; set; }
        public Nullable<int> id_doc_gia { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
