//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_PTUDHTTTHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDocGia
    {
        public LoaiDocGia()
        {
            this.DocGias = new HashSet<DocGia>();
        }
    
        public int id_loai_doc_gia { get; set; }
        public string ma_loai { get; set; }
        public string ten_loai { get; set; }
    
        public virtual ICollection<DocGia> DocGias { get; set; }
    }
}
